services:
  - name: Asset API
    plugin: asset_api
    source: kubernetes
    pod_name: asset-api-node01-8489d6cfc5-98llt
    namespace: asset-api
    max_restarts: 3
    time_window_minutes: 60

  - name: Runtime
    plugin: runtime
    source: docker
    container_id: 3365964fdbb5ab556c841abc5aa1a366bc97b867553e046dc4e60b0da67e23fc
    max_restarts: 3
    time_window_minutes: 60